from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse, JSONResponse
from app.database import get_scan_by_id
from app.models.schemas import ReconResult
import json
import io
from datetime import datetime

router = APIRouter()


@router.get("/export/{scan_id}/json")
async def export_json(scan_id: int):
    scan = get_scan_by_id(scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")

    filename = f"reconx_{scan['domain']}_{scan_id}.json"
    content = json.dumps(scan["result"], indent=2)

    return StreamingResponse(
        io.BytesIO(content.encode()),
        media_type="application/json",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/export/{scan_id}/txt")
async def export_txt(scan_id: int):
    scan = get_scan_by_id(scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")

    r = scan["result"]
    domain = r.get("domain", "unknown")
    scanned_at = scan.get("scanned_at", "")
    lines = []

    lines.append("=" * 60)
    lines.append(f"  ReconX Passive Recon Report")
    lines.append(f"  Domain  : {domain}")
    lines.append(f"  Scanned : {scanned_at}")
    lines.append(f"  Duration: {r.get('duration_ms', 0)}ms")
    lines.append("=" * 60)

    # WHOIS
    lines.append("\n[ WHOIS ]")
    whois = r.get("whois") or {}
    for key in ["registrar", "creation_date", "expiration_date", "registrant_org", "registrant_country", "dnssec"]:
        val = whois.get(key)
        if val:
            lines.append(f"  {key:<22}: {val}")
    ns = whois.get("name_servers", [])
    if ns:
        lines.append(f"  {'name_servers':<22}: {', '.join(ns)}")

    # DNS
    lines.append("\n[ DNS Records ]")
    dns = r.get("dns") or {}
    for rtype in ["A", "AAAA", "NS", "MX", "TXT", "CNAME"]:
        records = dns.get(rtype, [])
        if records:
            if rtype == "MX":
                for mx in records:
                    lines.append(f"  MX  : {mx.get('priority', '')} {mx.get('exchange', '')}")
            else:
                for rec in records:
                    lines.append(f"  {rtype:<4}: {rec}")

    # Subdomains
    subs = r.get("subdomains", [])
    lines.append(f"\n[ Subdomains ] ({len(subs)} found)")
    for s in subs[:50]:
        lines.append(f"  {s.get('subdomain', '')}")
    if len(subs) > 50:
        lines.append(f"  ... and {len(subs) - 50} more")

    # Headers
    lines.append("\n[ HTTP Headers ]")
    headers = r.get("headers") or {}
    if headers.get("error"):
        lines.append(f"  Error: {headers['error']}")
    else:
        lines.append(f"  Status Code : {headers.get('status_code', '—')}")
        lines.append(f"  Server      : {headers.get('server', '—')}")
        lines.append(f"  Security Score: {len(headers.get('security_headers_present', {}))} / {len(headers.get('security_headers_present', {})) + len(headers.get('missing_security_headers', []))} headers present")
        missing = headers.get("missing_security_headers", [])
        if missing:
            lines.append(f"  Missing     : {', '.join(missing)}")

    # Shodan
    lines.append("\n[ Shodan ]")
    shodan = r.get("shodan") or {}
    if shodan.get("error"):
        lines.append(f"  Error: {shodan['error']}")
    else:
        lines.append(f"  IP    : {shodan.get('ip', '—')}")
        lines.append(f"  Org   : {shodan.get('org', '—')}")
        lines.append(f"  Ports : {', '.join(str(p) for p in shodan.get('ports', []))}")
        vulns = shodan.get("vulns", [])
        if vulns:
            lines.append(f"  CVEs  : {', '.join(vulns)}")

    # AI Summary
    lines.append("\n[ AI Risk Summary ]")
    ai = r.get("ai_summary") or {}
    if ai.get("error"):
        lines.append(f"  Error: {ai['error']}")
    else:
        lines.append(f"  Overall Risk : {ai.get('overall_risk', 'Unknown')}")
        lines.append(f"  Summary      : {ai.get('plain_summary', '')}")
        lines.append("\n  Key Findings:")
        for f in ai.get("key_findings", []):
            lines.append(f"    [{f.get('severity','?').upper()}] {f.get('finding','')}")
        lines.append("\n  Recommendations:")
        for rec in ai.get("recommendations", []):
            lines.append(f"    • {rec}")

    lines.append("\n" + "=" * 60)
    lines.append("  Generated by ReconX — Passive Recon Only")
    lines.append("=" * 60)

    content = "\n".join(lines)
    filename = f"reconx_{domain}_{scan_id}.txt"

    return StreamingResponse(
        io.BytesIO(content.encode()),
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )